development:
  adapter: postgresql
  database: binable
  host: localhost
  username: johnkuehyoongfook
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: binable
  host: localhost
  username: johnkuehyoongfook
  pool: 5
  timeout: 5000